language: python

python:
  - "3.7"
  - "3.8"

before_install:
  - pip install pytest pytest-cov

install:
  - pip install -r requirements-dev.txt
  - python setup.py develop

script: make test-coverage

notifications:
  email:
    on_success: never
